# Huge thx to https://github.com/ad-m/github-push-action

name: Deploy Site on fschatbot.github.io

on:
  push:
    branch: [master]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Create local changes
        run: |
          npm clean-install --no-audit --no-fund
          CI='' npm run build
      - name: Commit files
        run: |
          rm -rf .git
          cd build
          git init
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add . -f
          git commit -m "${{ github.event.head_commit.message }} (${{ github.event.head_commit.id }}) [ci skip]"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          force: true
          directory: build
